### ISSUE TITLE
Cara run gimana kak?

### ISSUE THREAD

**Issue by 0xAndrs** [decryptable/gradient-network#2]

**Comment by decryptable** [comment]
Budayakan baca dokumentasi. Di halaman utama repository ini sudah terlihat jelas untuk dokumentasinya padahal. [baca disini](https://github.com/decryptable/gradient-network/blob/main/README.md)

**Comment by 0xAndrs** [comment]
Ini kan node . 
gak mau jalan tadi makanya sy tanya ada yg salah dimana? Sy run di VPS
